---
# tasks file for roles/kubernetes/install-kubevirt
- name: Install Kubevirt | apply operator
  shell: kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/{{ kubevirt_version }}/kubevirt-operator.yaml

- name: Install Kubevirt | apply cr
  shell: kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/{{ kubevirt_version }}/kubevirt-cr.yaml

- name: Install Kubevirt | copy kubvirt-config-map.yaml
  copy:
    src: kubvirt-config-map.yaml
    dest: "{{ network_deploy_dir }}/kubvirt-config-map.yaml"

- name: Install Kubevirt | apply kubvirt-config-map.yaml
  shell: kubectl create -f "{{ network_deploy_dir }}/kubvirt-config-map.yaml"
