#roles/<role>/task/main
#-install
#-config
#-triger handlers
#roles/defaults/main
#- many vars - use namespace. i.e. role_varname

---
- hosts: all
  gather_facts: false
  roles: 
    - role: kubernetes/host-common
      vars:
        kubernetes_version: 1.16.3-00
        nv_ovs_curl: curl -s https://2d0158bd54acb8195b4b8cc465e2ad839865f45dd45efcd5:@packages.nvidia.com/install/repositories/sdn/nv-ovs-2-12-0/script.deb.sh | bash
  tags: install-stuff


- hosts: kube-master
  gather_facts: false
  roles: 
    - role: kubernetes/master
      vars: 
        pod_network_cidr: 192.168.0.0/16
        service_cidr: 10.90.0.0/16
  tags: set-master

- hosts: kube-node
  gather_facts: false
  roles: 
    - role: kubernetes/node
  tags: set-nodes


 

- hosts: k8s-cluster
  gather_facts: false
  roles: 
    - role: kubernetes/network-plugin
      vars: 
        net_cidr: "{{ pod_network_cidr }}"
        svc_cidr: "{{ service_cidr }}"
        nv_k8s_yamls_version: devel
  tags: network

- hosts: k8s-cluster
  tasks:
  - debug:
      msg: "DEBUG {{ playbook_dir }} {{ inventory_hostname }}  {{ inventory_hostname_short }}"
  tags: foo

- hosts: k8s-cluster
  tasks:
  - debug:
      msg: "DEBUG {{ vars[inventory_hostname + '_start'] }}"
    when: is_kube_node
  tags: foo
 
