#roles/<role>/task/main
#-install
#-config
#-triger handlers
#roles/defaults/main
#- many vars - use namespace. i.e. role_varname

---
- hosts: all
  gather_facts: True
  become: True
  become_user: root
  tasks:
  - debug:
      msg: "DEBUG {{ playbook_dir }} {{ inventory_hostname }}  {{ inventory_hostname_short }} {{ hostvars[inventory_hostname].ansible_host }} {{ hostvars[inventory_hostname].ansible_distribution }} {{ ansible_os_family }}"
    tags: foo2
    #when: ansible_distribution == "CentOS"

- hosts: all
  gather_facts: false
  roles: 
    - role: kubernetes/host-common
      vars:
        ovn_encap_ip_prefix: 22
        cluster_default_route: 10.8.48.1
        kubernetes_version: 1.16.3-00
        ubuntu_nv_ovs_curl: curl -s https://2d0158bd54acb8195b4b8cc465e2ad839865f45dd45efcd5:@packages.nvidia.com/install/repositories/sdn/nv-ovs-2-12-0/script.deb.sh | bash
        centos_nv_ovs_curl: curl -s https://dde5dee3fddef955ebe8f8b548882e19180dfe1d9386e46c:@packages.nvidia.com/install/repositories/sdn/centos8-2-12-0-1/script.rpm.sh | os=el dist=7  bash
  tags: install-stuff


- hosts: kube-master
  gather_facts: false
  roles: 
    - role: kubernetes/master
      vars: 
        pod_network_cidr: 192.168.0.0/16
        service_cidr: 10.90.0.0/16
  tags: set-master

- hosts: kube-node
  gather_facts: false
  roles: 
    - role: kubernetes/node
  tags: set-nodes


 

- hosts: k8s-cluster
  gather_facts: false
  roles: 
    - role: kubernetes/network-plugin
      vars: 
        net_cidr: "{{ pod_network_cidr }}"
        svc_cidr: "{{ service_cidr }}"
        nv_k8s_yamls_version: devel
  tags: network


 
