#roles/<role>/task/main
#-install
#-config
#-triger handlers
#roles/defaults/main
#- many vars - use namespace. i.e. role_varname

---
- hosts: all
  gather_facts: True
  become: True
  become_user: root
  tasks:
  - debug:
      msg: "DEBUG {{ playbook_dir }} {{ inventory_hostname }}  {{ inventory_hostname_short }} {{ hostvars[inventory_hostname].ansible_host }} {{ hostvars[inventory_hostname].ansible_distribution }} {{ ansible_os_family }}"
    tags: foo2
    #when: ansible_distribution == "CentOS"

- hosts: all
  gather_facts: false
  roles: 
    - role: kubernetes/host-common
  tags: install-stuff


- hosts: kube-master
  gather_facts: false
  roles: 
    - role: kubernetes/master
      vars: 
        pod_network_cidr: "{{ pods_network_cidr }}"
        service_cidr: "{{ cluster_service_cidr }}"
  tags: set-master

- hosts: kube-node
  gather_facts: false
  roles: 
    - role: kubernetes/node
  tags: set-nodes

#- hosts: kube-master
  #gather_facts: false
  #roles: 
  #  - role: kubernetes/install-kubevirt
  #tags: install-kubevirt

- hosts: k8s-cluster
  gather_facts: false
  roles: 
    - role: kubernetes/network-plugin
      vars: 
        K8S_apiserver_address: "{{ hostvars[groups['kube-master'][0]].ansible_host }}"
        net_cidr: "{{ pods_network_cidr }}"
        svc_cidr: "{{ cluster_service_cidr }}"
  tags: network


 
