apiVersion: v1
kind: Pod
metadata:
  name: ub-pod
  labels:
    app: ub-pod
    name: ub-pod
spec:
  containers:
  - image: shaharklein/ub-gen:7
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: ub-pod

