apiVersion: v1
kind: Pod
metadata:
  name: ub-pod
  labels:
    app: ub-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-stream-net
spec:
  containers:
  - image: shaharklein/ub-gen:7
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: ub-pod
    resources:
     requests:
       intel.com/sriov_stream: '1'
     limits:
       intel.com/sriov_stream: '1'

