---
# tasks file for roles/kubernetes/network-plugin
#
#
- debug:
    msg: "DEBUG {{ playbook_dir }} {{ inventory_hostname }}  {{ inventory_hostname_short }}"

- name: Network | Download nv-k8s multus yamls
  shell: curl  -o {{ playbook_dir }}/roles/kubernetes/network-plugin/templates/{{ item }} --resolve gitlab-master.nvidia.com:443:127.0.0.1 https://gitlab-master.nvidia.com/sdn/k8s-yaml/raw/{{ nv_k8s_yamls_version }}/multus/{{ item }}
  with_items:
    - multus.yaml
    - sriov-public-net-crd.yaml
    - sriov-storage-net-crd.yaml
    - sriov-stream-net-crd.yaml
  delegate_to: localhost
  run_once: true


- name: Handle nv-k8s-yamls
  import_tasks: handle-nv-k8s-yamls.yaml
  tags: nv-k8s-yamls

- name: Network | | Cleanup | delete sriov device plugin
  shell: kubectl delete -f {{ network_deploy_dir }}/{{ item }}
  ignore_errors: true
  with_items:
    - sriov-dp.yaml
  when: is_kube_master

- name: Network | Cleanup | delete ovn-k8s
  shell: kubectl delete -f {{ network_deploy_dir }}/{{ item }}
  ignore_errors: true
  no_log: true
  args:
    warn: false
  with_items:
    - ovnkube-node.yaml
    - ovnkube-master.yaml
    - ovnkube-db.yaml
    - ovn-setup.yaml
  when: is_kube_master

- name: Network | Cleanup | delete Multus
  shell: kubectl delete -f {{ network_deploy_dir }}/{{ item }}
  ignore_errors: true
  no_log: true
  args:
    warn: false
  with_items:
    - multus.yaml
  when: is_kube_master

- name: Network | Zeroize SRIOV
  shell: echo 0 > /sys/class/net/{{ item.dev_name }}/device/sriov_numvfs
  with_items: "{{ sriov_devices }}"
  when: is_kube_node

- name: Network | Set SRIOV
  shell: echo {{ item.num_vfs }} > /sys/class/net/{{ item.dev_name }}/device/sriov_numvfs
  with_items: "{{ sriov_devices }}"
  when: is_kube_node

- name: Network | deploy Multus
  shell: kubectl apply -f {{ network_deploy_dir }}/{{ item }}
  with_items:
    - multus.yaml
    - sriov-public-net-crd.yaml 
    - sriov-storage-net-crd.yaml 
    - sriov-stream-net-crd.yaml
  when: is_kube_master

- name: Network | deploy ovn-k8s
  shell: kubectl apply -f {{ network_deploy_dir }}/{{ item }}
  with_items:
    - ovn-setup.yaml
    - ovnkube-db.yaml
    - ovnkube-master.yaml
    - ovnkube-node.yaml
  when: is_kube_master

- name: Network | Creates the sriov dp config directory
  file:
    path: /etc/pcidp
    state: directory
  when: is_game_host

- name: Handle host sriov cni conf
  import_tasks: host-sriov-config.yaml
  tags: host-sriov-config

- name: Network | deploy sriov device plugin
  shell: kubectl apply -f {{ network_deploy_dir }}/{{ item }}
  with_items:
    - sriov-dp.yaml
  when: is_kube_master

- name: Network | deploy sriov CNI
  shell: kubectl apply -f {{ network_deploy_dir }}/{{ item }}
  with_items:
    - sriov-cni.yaml
  when: is_kube_master

# zero and set sriov vf num
# apply multus
# apply ovn
# apply sriov dp
# apply sriov-cni
#
