---
# tasks file for roles/kubernetes/network-plugin
#
#
- debug:
    msg: "DEBUG {{ playbook_dir }} {{ inventory_hostname }}  {{ inventory_hostname_short }}"

- name: Handle nv-k8s-yamls
  import_tasks: handle-nv-k8s-yamls.yaml
  tags: nv-k8s-yamls

- name: Network | Cleanup | delete sriov device plugin
  shell: kubectl delete -f {{ network_deploy_dir }}/{{ item }}
  ignore_errors: true
  no_log: true
  args:
    warn: false
  with_items:
    - sriov-dp.yaml
  when: is_kube_master
  tags: 
  - network-clean
  - no-sriov

- name: Network | Cleanup | delete ovn-k8s
  shell: kubectl delete -f {{ network_deploy_dir }}/{{ item }}
  ignore_errors: true
  no_log: true
  args:
    warn: false
  with_items:
    - ovnkube-node.yaml
    - ovnkube-master.yaml
    - ovnkube-db.yaml
    - ovn-setup.yaml
  when: is_kube_master
  tags: network-clean

- name: Network | Cleanup | delete Multus
  shell: kubectl delete -f {{ network_deploy_dir }}/{{ item }}
  ignore_errors: true
  no_log: true
  args:
    warn: false
  with_items:
    - multus.yaml
  when: is_kube_master
  tags: network-clean

- name: Network | Zeroize SRIOV
  shell: echo 0 > /sys/class/net/{{ item.dev_name }}/device/sriov_numvfs
  with_items: "{{ sriov_devices }}"
  when: is_kube_node
  tags:
  - no-sriov

- name: Network | Set SRIOV
  shell: echo {{ item.num_vfs }} > /sys/class/net/{{ item.dev_name }}/device/sriov_numvfs
  with_items: "{{ sriov_devices }}"
  when: is_kube_node
  tags:
  - no-sriov

- name: Network | deploy Multus
  shell: kubectl apply -f {{ network_deploy_dir }}/{{ item }}
  with_items:
    - multus.yaml
    - sriov-public-net-crd.yaml 
    - sriov-storage-net-crd.yaml 
    - sriov-stream-net-crd.yaml
  when: is_kube_master

- name: Network | deploy ovn-k8s
  shell: kubectl apply -f {{ network_deploy_dir }}/{{ item }}
  with_items:
    - ovn-setup.yaml
    - ovnkube-db.yaml
    - ovnkube-master.yaml
    - ovnkube-node.yaml
  when: is_kube_master

- name: Network | Create the sriov dp config directory
  file:
    path: /etc/pcidp
    state: directory
  when: is_game_host
  tags:
  - no-sriov

- name: Handle host sriov cni conf
  import_tasks: host-sriov-config.yaml
  tags: host-sriov-config
  tags:
  - no-sriov

- name: Network | deploy sriov device plugin
  shell: kubectl apply -f {{ network_deploy_dir }}/{{ item }}
  with_items:
    - sriov-dp.yaml
  when: is_kube_master
  tags:
  - no-sriov

- name: Network | deploy sriov CNI
  shell: kubectl apply -f {{ network_deploy_dir }}/{{ item }}
  with_items:
    - sriov-cni.yaml
  when: is_kube_master
  tags:
  - no-sriov

# zero and set sriov vf num
# apply multus
# apply ovn
# apply sriov dp
# apply sriov-cni
#
