

is_kube_master: "{{ inventory_hostname in groups['kube-master'] }}"
is_kube_node: "{{ inventory_hostname in groups['kube-node'] }}"
is_game_host: "{{ inventory_hostname in groups['game-hosts'] }}"

sriov_devices:
        #- {dev_name: enp175s0, num_vfs: 4}
  - {dev_name: "{{ game_server_sriov_stream_pf }}", num_vfs: 4}

node-09_stream_range_start: 10.1.12.121
node-09_stream_range_end: 10.1.12.140
node-12_stream_range_start: 10.1.12.141
node-12_stream_range_end: 10.1.12.160
sdn-test2_stream_range_start: 10.1.12.121
sdn-test2_stream_range_end: 10.1.12.140
sdn-test3_stream_range_start: 10.1.12.141
sdn-test3_stream_range_end: 10.1.12.160
rlab-net-srv-27_stream_range_start: 10.1.12.161
rlab-net-srv-27_stream_range_end: 10.1.12.180
rlab-net-12_stream_range_start: 10.1.12.161
rlab-net-12_stream_range_end: 10.1.12.180

#ovn_gateway_opts: "--gateway-interface=brenp175s0 --gateway-nexthop=10.50.55.1"
ovn_gateway_opts: ""


any_errors_fatal: true

cluster_default_route: 10.8.48.1
ovn_encap_ip_prefix: 22
cluster_dns1: 8.8.8.8
cluster_dns2: 103.247.36.36

pods_network_cidr: 192.168.0.0/16
cluster_service_cidr: 10.90.0.0/16
nv_k8s_yamls_version: devel
network_deploy_dir: /root/k8snet-deploy


docker_version: 3:18.09.1-3.el7
kubernetes_version: 1.16.3-00
kubevirt_version: v0.27.0
virtctl_location: https://github.com/kubevirt/kubevirt/releases/download/v0.26.4/virtctl-v0.26.4-linux-amd64

ubuntu_nv_ovs_curl: curl -s https://2d0158bd54acb8195b4b8cc465e2ad839865f45dd45efcd5:@packages.nvidia.com/install/repositories/sdn/nv-ovs-2-12-0/script.deb.sh | bash
#centos_nv_ovs_curl: curl -s https://dde5dee3fddef955ebe8f8b548882e19180dfe1d9386e46c:@packages.nvidia.com/install/repositories/sdn/centos8-2-12-0-1/script.rpm.sh | os=el dist=7  bash

#centos_nv_ovs_curl: curl -s https://235d694c9659322992cdb8268f5e3b5fb0c3e4e8fd833447:@packages.nvidia.com/install/repositories/sdn/nv-ovs-2-12-0-2/script.rpm.sh | bash
#ovs_version: 2.12.0-2

centos_nv_ovs_curl: curl -s https://38a0484b1764796f6ac26ab0eb03336ee168ab7fb3ac03a9:@packages.nvidia.com/install/repositories/sdn/nv-ovs-2-13-0-1/script.rpm.sh | bash
#ovs_version: -2.13.0
ovs_version: 


#centos_nv_ovs_curl: curl -s https://212c509f7a05c079d2fdc312ad7e1265c4666f4fb629a000:@packages.nvidia.com/install/repositories/sdn/nv-ovs-2-13-90-1/script.rpm.sh |  bash
#ovs_version: 2.13.90-1.el8
