

is_kube_master: "{{ inventory_hostname in groups['kube-master'] }}"
is_kube_node: "{{ inventory_hostname in groups['kube-node'] }}"
is_game_host: "{{ inventory_hostname in groups['game-hosts'] }}"

sriov_devices:
        #- {dev_name: enp175s0, num_vfs: 4}
  - {dev_name: ens1, num_vfs: 4}

game_server_sriov_stream_pf: ens1 

#node-09_stream_range_start: 10.1.12.121
#node-09_stream_range_end: 10.1.12.140
#node-12_stream_range_start: 10.1.12.141
#node-12_stream_range_end: 10.1.12.160
sdn-test2_stream_range_start: 10.1.12.121
sdn-test2_stream_range_end: 10.1.12.140
sdn-test3_stream_range_start: 10.1.12.141
sdn-test3_stream_range_end: 10.1.12.160

#ovn_gateway_opts: "--gateway-interface=brenp175s0 --gateway-nexthop=10.50.55.1"
ovn_gateway_opts: ""


any_errors_fatal: true

cluster_default_route: 10.8.48.1
ovn_encap_ip_prefix: 22
cluster_dns1: 8.8.8.8
cluster_dns2: 103.247.36.36

