---
# tasks file for reset
#
#

- name: Install network-scripts
  package:
    name: network-scripts
    state: latest
  become: yes
  ignore_errors: yes

- name: Stop NetworkManager
  systemd:
    state: stopped
    enabled: no
    name: NetworkManager
  ignore_errors: yes

- name: Remove NetworkManager
  package:
    name: NetworkManager
    state: absent
  become: yes
  ignore_errors: yes




- name: Reset | set ifcfg
  template:
    src: ifcfg.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ ovn_encap_dev }}
    force: yes

- name: Reset | remove br ifcfg
  file: 
    path: /etc/sysconfig/network-scripts/ifcfg-br{{ ovn_encap_dev }}
    state: absent

- name: run network-scripts
  systemd:
    state: restarted
    enabled: yes
    name: network

- name: Clean ovs bridges
  shell: ovs-vsctl list-br | xargs -r -l ovs-vsctl del-br && systemctl restart network
  args:
    warn: false
  ignore_errors: true
  tags: 
  - ovs
  - cleanup


- name: Clean ovn on master
  file:
    state: "{{ item }}"
    path: "/var/lib/openvswitch"
  with_items:
    - absent
    - directory

- name: Reset | Clean ovs old db
  file:
    state: "{{ item }}"
    path: "/etc/openvswitch"
  with_items:
    - absent
    - directory
  tags: reset

- name: reset | stop services
  systemd:
    state: stopped
    enabled: no
    name: "{{ item }}"
  loop: [ 'openvswitch', 'docker', 'kubelet' ]
  ignore_errors: true

- name: Reset | clear repos files identify
  find:
    paths: /etc/yum.repos.d
    excludes: CentOS*
  register: repos_to_delete
  tags: d7

- name: debug
  debug:
     msg: "{{ item.path }}" 
  with_items: "{{ repos_to_delete.files }}"
  tags: d8



- name: Reset | clear repos
  file: 
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ repos_to_delete.files }}"
  tags: d7

- name: Reset | remove ovs, docker, kubernetes
  package:
    name: "{{ item }}"
    state: absent
  loop: [ 'openvswitch', 'kubeadm', 'kubelet', 'docker-ce' ]
  ignore_errors: true
  tags: reset

