---
# tasks file for roles/kubernetes/host-common
#
#

- name: Assign inventory name to hostnames
  hostname:
    name: "{{ inventory_hostname }}"

- name: Add hostname resolv
  lineinfile:
    dest: /etc/hosts
    line: "{{ ansible_host }} {{ inventory_hostname }}"
    state: present

- name: Run Ubuntu host common tasks
  import_tasks: ubuntu-common.yaml
  when: ansible_distribution == "Ubuntu"

- name: Run CentOS host common tasks
  import_tasks: centos-common.yaml
  when: ansible_distribution == "CentOS"

- name: Host | Create the pem dir
  file:
    path: /etc/ovn
    state: directory

- name: Host | Copy pem files
  copy:
    src: "pem/{{ item }}"
    dest: "/etc/ovn/{{ item }}"
  with_items:
    - ca-cert.pem
    - ovncontroller-cert.pem
    - ovncontroller-privkey.pem
    - ovnnb-cert.pem
    - ovnnb-privkey.pem
    - ovnnorthd-cert.pem
    - ovnnorthd-privkey.pem
    - ovnsb-cert.pem
    - ovnsb-privkey.pem
  tags: pem


  #- name: get ovn-kube-util
  #shell: docker run --rm -v /usr/bin:/host/usr/bin -it quay.io/gmoodalbail/deliver-ovn-util:v0.1

  #- name: set phys br
  #shell: ovn-kube-util nics-to-bridge {{ game_server_sriov_stream_pf }}

  #  ovs-vsctl set Open_vSwith . external_ids:ovn-encap-ip=""
- name: set encap ip
  shell: ovs-vsctl set Open_vSwitch . external_ids:ovn-encap-ip={{ hostvars[inventory_hostname].ovn_encap_ip }}

 
   
   
