---
# tasks file for roles/kubernetes/host-common
#
- name: Clean apt sources list
  file:
    state: "{{ item }}"
    path: "/etc/apt/sources.list.d"
  with_items:
    - absent
    - directory

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: add Kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add Kubernetes' APT repository
  apt_repository:
   repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
   state: present
   update_cache: yes

- name: install kubelet
  apt:
    name: kubelet={{ kubernetes_version }}
    state: present
    force: yes
    #update_cache: true

- name: install kubeadm
  apt:
    name: kubeadm={{ kubernetes_version }}
    state: present
    force: yes

- name: install kubectl on the master node
  apt:
    name: kubectl={{ kubernetes_version }}
    state: present
    force: yes
  when: is_kube_master

- name: install openshift python for ansible k8s module
  pip:
    name: openshift
  when: is_kube_master
  tags: openshift

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes force=yes name=docker-ce state=latest

- name: remove ovs
  apt:
    name: "{{ item }}"
    state: absent
  loop: [ 'openvswitch-switch', 'openvswitch-common', 'libopenvswitch']
  tags: ovs

- name: set nv ovs repo
  shell: "{{ nv_ovs_curl }}"
  args:
    warn: false
  tags: ovs

- name: install ovs
  apt: 
    name: openvswitch-switch
    state: present
  tags: ovs

- name: Get a list of all pods from any namespace
  k8s_facts:
    kind: Pod
    namespace: kube-system
  register: pod_list
  tags: foo
  when: is_kube_master

- name: 
  debug:
    var: pod_list
  tags: foo
  when: is_kube_master
 
   
   
